export const GET_WORKFLOWS = 'GET_WORKFLOWS' as const;
export const ADD_WORKFLOW = 'ADD_WORKFLOW' as const;
export const DELETE_WORKFLOW = 'DELETE_WORKFLOW' as const;
export const UPDATE_WORKFLOW = 'UPDATE_WORKFLOW' as const;
export const UPDATE_WORKFLOW_SECURITY = 'UPDATE_WORKFLOW_SECURITY' as const;
export const UPDATE_WORKFLOW_STATE = 'UPDATE_WORKFLOW_STATE';
export const ASSIGN_WORKFLOW = 'ASSIGN_WORKFLOW' as const;
export const VALIDATE_WORKFLOW = 'VALIDATE_WORKFLOW' as const;
export const CLEAR_LAST_CREATED_WORKFLOW = 'CLEAR_LAST_CREATED_WORKFLOW';
export const GET_WORKFLOW = 'GET_WORKFLOW' as const;

export const LIST_STATES = 'LIST_STATES';
export const ADD_STATE = 'ADD_STATE';
export const UPDATE_STATE = 'UPDATE_STATE';
export const DELETE_STATE = 'DELETE_STATE';

export const LIST_TRANSITIONS = 'LIST_TRANSITIONS';
export const GET_TRANSITION = 'GET_TRANSITION';
export const ADD_TRANSITION = 'ADD_TRANSITION';
export const UPDATE_TRANSITION = 'UPDATE_TRANSITION';
export const DELETE_TRANSITION = 'DELETE_TRANSITION';
